config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do

  # tanto WWW como SIN subdomain, hacen redirect
  constraints(subdomain: ['www','']) do
    scope as: 'www' do
      root to: 'country_selector#show'
      get '*path' => 'country_selector#show'
    end
  end

  draw :es_redirections
  draw :mx_redirections
  
  # el app solo acepta routes bajo el subdomain de su pais
  constraints(subdomain: Rails.configuration.x.app_country) do

    devise_for :super_users, controllers: {
      sessions: 'super/users/sessions',
      passwords: 'super/users/passwords',
    }

    ### SUPER
    namespace :super do
      resources :banners do
        get :toggle_recommended, on: :member
        post :delete_multiple_banners, on: :collection 
      end

      resources :payments
      resources :users
      resources :banner_categories
      resources :payment_types
      resources :pack_discounts
      resources :super_users
      resources :app_settings
      resources :html_texts
      resources :image_banners
      resources :external_banners

      get 'reportes'                       => 'reports#index',              as: 'reports'
      get 'reportes/titulos_duplicados'    => 'reports#duplicated_title',   as: 'duplicated_title_reports'
      get 'reportes/contenidos_duplicados' => 'reports#duplicated_content', as: 'duplicated_content_reports'
      get 'reportes/titulos_similares'     => 'reports#similar_title',      as: 'similar_title_reports'
      get 'reportes/contenidos_similares'  => 'reports#similar_content',    as: 'similar_content_reports'
      get 'reportes/usuarios'              => 'reports#users',              as: 'users_reports'
      get 'reportes/usuarios_semanal'      => 'reports#weekly_users',       as: 'weekly_users_reports'

      root to: 'users#index'

      match 'similar_text' => 'banners#similar_text', as: :similar_text, via: [:get, :post]
    end

    ### FRONTEND

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      # omniauth_callbacks: "users/omniauth_callbacks",
    }
    resources :users
    resources :banners

    get  'nuevo-anuncio-y-registro' => 'banners#anon_new_banner', as: 'anon_new_banner'
    post 'anon_create_banner' => 'banners#anon_create_banner', as: 'anon_create_banner'
    get '/users/sign_up', to: redirect('nuevo-anuncio-y-registro', status: 301)

    resources :cities do
      collection do
        get :search
      end
    end

    get '/anuncios-eroticos/escorts-y-putas/distrito-federal', to: redirect('/anuncios-eroticos/escorts-y-putas/distrito-federal-df', status: 301)

    # search url pretty para SEO
    # uso el keyword "putas" para crear variaciones de patrones segun los params pasados
    get '/nuevo-anuncio' => 'banners#new', as: "new_post"
    get '/anuncios-eroticos/:category/:state(/contactos/:term)' => "posts#index", as: "search_state_term"
    get '/anuncios-eroticos/:category(/contactos/:term)'        => "posts#index", as: "search_term"
    get '/anuncios-eroticos/:category(/:state)(/:city)(/:term)' => "posts#index", as: "friendly_search"
    get '/anuncios-eroticos/:category(/:state)(/:city)(/:term)' => "posts#index", as: "full_search"
    get '/anuncios-eroticos/:category' => "posts#index", as: "only_category"


    get '/anuncio-erotico/:id' => "posts#show", as: "post_with_category"
    get '/posts/:id/get_phone' => "posts#show_phone", as: 'post_phone'

    resources :posts, path: 'anuncios' do
      get :search, on: :collection
    end
    get '/anuncios-eroticos/:category_id/:state_id'          => 'posts#search_single_state', as: :search_single_state
    get '/anuncios-eroticos/:category_id/:state_id/:city_id' => 'posts#search_single_city',  as: :search_single_city

    resources :banner_contact_requests
    resources :user_favorites do
      post :toggle, on: :member
    end

    resources :sent_favorites
    resources :feedback_requests

    # pagos
    get '/historial-pagos' => 'payments#index', as: 'my_payments'
    get '/historial-pagos/:id' => 'payments#show', as: 'view_payment'
    get '/payments/est_price' => 'payments#get_price', as: 'est_price'
    resources :payments

    # paypal checkout
    get '/paypal/checkout' => 'paypal#checkout', as: 'paypal_checkout'
    get '/paypal/success' => 'paypal#success', as: 'paypal_success'
    get '/paypal/fail' => 'paypal#fail', as: 'paypal_fail'

    # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

    get '/mejora-adultguia' => 'feedback_requests#new', as: "feedback"
    get '/aviso-legal' => 'statics#aviso_legal', as: "aviso_legal"
    get '/politica-privacidad-cookies' => 'statics#politica_privacidad', as: "politica_privacidad"

    get 'feed' => 'posts#feed'

    root to: 'posts#index'

    get '/remote-cities' => 'cities#search', as: "remote_cities"

    post 'set_paid_location' => 'banners#set_paid_location', as: 'set_paid_location'

    get 'validar_anuncio' => 'banners#validate', as: 'validate_banner'
    get 'resend_email_validation' => 'banners#resend_email_validation', as: 'resend_email_validation'

  end

end

app/controllers/banners_controller.rb
class BannersController < BaseController

  before_action :authenticate_user!, except: [:anon_new_banner, :anon_new_user, :anon_create_banner, :anon_create_user]
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  def index
    @banners = Banner.unscoped.non_deleted.where(user: current_user).includes(:phone_views).page(params[:page]).per(10)
  end

  def show
  end

  def new
    @banner = current_user.banners.new
    # inherit user location
    @banner.email = current_user.email
    @banner.state = current_user.state if current_user.state.present?
    @banner.city = current_user.city if current_user.city.present?
  end

  def edit
  end

  def create
    @banner = current_user.banners.new(banner_params)
    @banner.validated = false

    if @banner.save
      BannerMailer.validate(@banner).deliver_now
      redirect_to post_permalink(@banner), notice: '¡Anuncio creado con éxito! (Recibiste un email para validar tu anuncio)'
    else
      render :new
    end
  end

  def update
    if @banner.update(banner_params)
      redirect_to edit_banner_path(@banner), notice: 'Cambios guardados'
    else
      render :edit
    end
  end

  def destroy
    @banner.destroy
    redirect_to banners_url, notice: 'Anuncio eliminado'
  end

  def set_paid_location
    paid_banners = current_user.paid_banner_locations.where(banner_id: params[:paid_banner_location][:banner_id])
    
    if paid_banners.any?
      paid_banner = paid_banners.last
      paid_banner.update_attributes(
        banner_id: params[:paid_banner_location][:banner_id],
        state_id:  params[:paid_banner_location][:state_id],
        city_id:   params[:paid_banner_location][:city_id],
        banner_category_id: params[:paid_banner_location][:banner_category_id],
      )

      notice_message = "Ubicación actualizada correctamente"
      redirect_to :back, notice: notice_message
    else
      paid_banner_location = PaidBannerLocation.new(
        user_id:   current_user.id,
        banner_id: params[:paid_banner_location][:banner_id],
        state_id:  params[:paid_banner_location][:state_id],
        city_id:   params[:paid_banner_location][:city_id],
        banner_category_id: params[:paid_banner_location][:banner_category_id]
      )

      if paid_banner_location.save
        notice_message = "Ubicación guardada correctamente"
        redirect_to :back, notice: notice_message
      else
        notice_message = "Ocurrió un error guardando la ubicación: #{paid_banner_location.errors.full_messages.join(', ')}"
        redirect_to :back, alert: notice_message
      end
    end
  end

  # Anonymous
  def anon_new_banner    
    case Rails.configuration.x.app_country
    when 'mx'
      then
      city = City.where(slug: 'benito-juarez', state_slug: 'distrito-federal-df').last
    when 'es'
      then
      city = City.where(slug: 'madrid', state_slug: 'madrid').last
    else
      city = City.where(slug: 'madrid', state_slug: 'madrid').last
    end

    @banner = Banner.new
  end

  def anon_create_banner
    @user = User.find_for_authentication(email: params[:user_email])
    
    if @user.present? && @user.valid_password?(params[:user_password])
      @banner = @user.banners.new(banner_params)

      @banner.validated = false
      if @banner.save
        BannerMailer.validate(@banner).deliver_now
        sign_in(@user, scope: :user) and redirect_to post_with_category_path(id: @banner.id), notice: '¡Anuncio creado con éxito! (Recibiste un email para validar tu anuncio)'
      else
        render :anon_new_banner
      end
    else
      first_name = params[:user_email].split("@").first
      last_name  = first_name

      @user = User.new(
        first_name: first_name,
        last_name:  last_name,
        state_id:   banner_params[:state_id],
        city_id:    banner_params[:city_id],
        email:      params[:user_email],
        password:   params[:user_password],
        password_confirmation: params[:user_password],
        confirmed_at: Time.now.utc
      )
      
      @banner = @user.banners.new(banner_params)
      @banner.validated = false

      if @user.save
        if @banner.save
          BannerMailer.validate(@banner).deliver_now

          #sign_in(@user, scope: :user) and redirect_to post_with_category_path(id: @banner.id), notice: '¡Anuncio creado con éxito!'
          sign_in(@user, scope: :user) and redirect_to only_category_path(category: @banner.category.slug), notice: '¡Anuncio creado con éxito! (Recibiste un email para validar tu anuncio)'
        else
          render :anon_new_banner
        end
      else
        render :anon_new_banner
      end

    end
  end

  def validate
    banner = Banner.unscoped.find_by(validation_uuid: params[:uuid])
    if banner.present?
      banner.update_attribute(:validated, true)
      banner.save
      redirect_to post_with_category_path(id: banner.id), notice: '¡Anuncio validado con éxito!'
    else
      redirect_to root_path
    end
  end

  def resend_email_validation
    banner = Banner.unscoped.where(user: current_user).friendly.find(params[:id])
    if banner.present?
      BannerMailer.validate(banner).deliver_now
      redirect_to :back, notice: 'Email de validación enviado con éxito!'
    else
      redirect_to root_path
    end
  end

  private
    def set_banner
      @banner = Banner.unscoped.non_deleted.where(user: current_user).friendly.find(params[:id])
    end

    def banner_params
      params.require(:banner).permit(:banner_category_id, :title, :visible_from, :email, :phone, :description, :state_id, :city_id, :price, :alerts, images_attributes: [:_destroy, :id, :file, :file_cache, :position, :title, :alt])
    end
end

app/controllers/super/banners_controller.rb
module Super

  class BannersController < Super::BaseController
    
    def index
      @q = Banner.ransack(params[:q])
      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @banners = @q.result(distinct: true).page(params[:page]).per(20)
    end

    def edit
      @banner = Banner.friendly.find(params[:id])
    end

    def update
      @banner = Banner.friendly.find(params[:id])
      if @banner.update(s_params)
        redirect_to edit_super_banner_url(@banner), notice: "Cambios guardados"
      else
        render :edit
      end
    end

    def destroy
      banner = Banner.friendly.find(params[:id])
      banner.destroy
      redirect_to super_banners_url, notice: 'Anuncio eliminado'
    end

    def toggle_recommended
      banner = Banner.friendly.find(params[:id])
      banner.toggle :recommended
      banner.save
      
      notice_text = (banner.recommended == true) ? 'Anuncio marcado como recomendado' : 'Anuncio desmarcado como recomendado'
      redirect_to super_banners_url, notice: notice_text
    end

    def delete_multiple_banners
      params["delete_banner_id"].each do |banner_id|
        banner = Banner.find(banner_id)
        banner.destroy
      end

      redirect_to super_banners_url, notice: 'Anuncios eliminados'
    end

    def similar_text
      if request.post?
        #@similar_text = params[:text1].similar(params[:text2])
        @similar_text = Banner.compare_texts(params[:text1], params[:text2])
      end
    end

    private

    def s_params
      params.require(:banner).permit!
    end
    
  end

end

app/helpers/banners_helper.rb
module BannersHelper

  def set_category(banner)
    if banner.paid_banner_location
      banner.paid_banner_location.banner_category_id
    else
      #banner.banner_category_id
      nil
    end
  end

  def set_state(banner)
    if banner.paid_banner_location
      banner.paid_banner_location.state_id
    else
      nil
    end
  end

  def set_city(banner)
    if banner.paid_banner_location
      banner.paid_banner_location.city_id
    else
      nil
    end
  end

end

app/views/banners/_form.html.erb
<% content_for :js_init do %>
  <script>
    (function(){
      var form = new BannerForm(<%= raw @banner.to_json %>);
    })();
  </script>
<% end %>
<% is_super = params[:controller].include?('super/') %>

<div id="gmap"></div>

<div class="row">
  
  <% form_url = is_super ? [:super, @banner] : @banner %>
  <%= simple_form_for form_url, html: {class: 'js-banner-form', id: "banner-form"} do |f| %>

  <div class="col-md-4 col-md-push-8">
    
    <% unless is_super %>
      <div class="post-advices">
        <h3>No olvides</h3>
        <ul>
          <li><i class="fa fa-check"></i> Elegir un título llamativo que no se repita en otros anuncios.</li>
          <li>
            <i class="fa fa-check"></i>
            <span>Publicar anuncios originales, NO repitas textos.</span>
            <br>
            <span style="color: red; padding-left: 14px">O SERAN ELIMINADOS</span>
          </li>
          <li><i class="fa fa-check"></i> Poner fotos para que tu anuncio tenga más éxito.</li>
          <li><i class="fa fa-check"></i> Poner el anuncio en la categoría adecuada.</li>
          <li><i class="fa fa-check"></i> <strong>Importante</strong>: revisar que tu teléfono sea el correcto.</li>
        </ul>
      </div>
    <% end %>
    
    <div class="banner-images">
      <%= link_to_add_association 'Agregar foto', f, :images, 'data-association-insertion-node'=>'.wrapper', 'data-association-insertion-traversal'=>'siblings', class: 'btn btn-default pull-right', 'data-association-insertion-method'=>'append', partial: "banners/image_fields" %>

      <h3>Fotos</h3> 
      <p class="text-info hint"><i class="fa fa-info-circle"></i> Puedes cambiar el orden de las fotos arrastrándolas con el icono de flechas. <strong>La primera imagen será la destacada</strong> y se mostrará en el listado de anuncios.</p>

      <div class="wrapper">
        <%= f.simple_fields_for :images do |i| %>
          <%= render 'banners/image_fields', f: i %>
        <% end %>
      </div>
    </div>
    
  </div>

  <div class="col-md-8 col-md-pull-4">

    <h2><%= title (@banner.new_record? ? "Nuevo anuncio" : "Editar anuncio") %></h2>
    
      <%= f.error_notification %>
      <%#= @banner.errors.inspect %>

      <%= f.input :title, label: "Título" %>
      <div class="row">
        <div class="col-md-6">
          <%= f.association :category, label: "Categoría", include_blank: "- Selecciona" %>
        </div>
        <div class="col-md-6">
          <%= f.input :price, label: "Precio del servicio" %>
        </div>
      </div>
      
      <label class="control-label">Localización</label>
      <div class="row">
        <div class="col-md-6">
          <%= f.association :state, label: false, collection: State.all, include_blank: t('provincia'), input_html:{class: 'selectize-states'} %>
        </div>
        <div class="col-md-6">
          <% selected_city = @banner.state ? @banner.state.cities : [] %>
          <%= f.association :city, collection: selected_city, label: false, placeholder: 'Ciudad', input_html:{class: 'selectize-cities'} %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-12">
          <%= f.input :description, label: "Descripción", input_html: {class: 'summernote', data: {}} %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-6">
          <%= f.input :email, label: "Email", hint: 'Tu email NO será publicado' %>
        </div>
        <div class="col-md-6">
          <%= f.input :phone, label: "Teléfono", hint: "Sin espacios. #{Rails.application.secrets.phone_digits} caracteres exactos." %>
        </div>
      </div>

      <%= f.input :alerts, label: "Recibir alertas" %>
      <%= f.input :visible_from, label: 'Visible a partir de' %>
      
      <% if is_super %>
        <div class="well">
          <h4>SEO</h4>
          <%= f.input :meta_title %>
          <%= f.input :meta_desc %>
        </div>
      <% end %>
      
      <hr>
      <%= f.submit "Guardar anuncio", class: 'btn btn-lg btn-success' %>
      <%= link_to "Cancelar y volver", (is_super ? super_banners_url : banners_path), class: 'btn btn-lg btn-default' %>

  </div>

  <% end %>

</div>

app/views/banners/_image_fields.html.erb
<div class="nested-fields image">
  <%= f.input_field :position, as: :hidden %>
  <%= f.input_field :id, as: :hidden %>

  <div class="actions">
    <a href="#" class=" move-up"><i class="fa fa-arrow-up"></i></a>
    <a href="#" class=" move-down"><i class="fa fa-arrow-down"></i></a>
    <%= link_to_remove_association '<i class="fa fa-times"></i>'.html_safe, f, class: 'remove-item' %>
  </div>

  <%= f.input :file, label: "Imagen" %>
  <%= f.input_field :file_cache, as: :hidden %>
  
  <% if f.object.file? %>
    <%= link_to image_tag(f.object.file.url(:thumb)), f.object.file.url(:large), "data-fancybox" => "images", rel: 'gallery' %>
  <% end %>
</div>

app/views/banners/anon_new_banner.html.erb
<% content_for :meta_robots do %>
  <meta name="robots" content="noindex,follow" />
<% end %>

<% content_for :js_init do %>
  <script>
    (function(){
      var form = new BannerForm(<%= raw @banner.to_json %>);
    })();
  </script>
<% end %>

<div class="row">
  
  <%= simple_form_for @banner, url: anon_create_banner_path, method: :post, html: {class: 'js-banner-form', id: "banner-form"} do |f| %>

  <div class="col-md-4 col-md-push-8">
    
    <div class="post-advices">
      <h3>No olvides</h3>
      <ul>
        <li><i class="fa fa-check"></i> Elegir un título llamativo que no se repita en otros anuncios.</li>
        <li>
          <i class="fa fa-check"></i>
          <span>Publicar anuncios originales, NO repitas textos.</span>
          <br>
          <span style="color: red; padding-left: 14px">O SERAN ELIMINADOS</span>
        </li>
        <li><i class="fa fa-check"></i> Poner fotos para que tu anuncio tenga más éxito.</li>
        <li><i class="fa fa-check"></i> Poner el anuncio en la categoría adecuada.</li>
        <li><i class="fa fa-check"></i> <strong>Importante</strong>: revisar que tu teléfono sea el correcto.</li>
      </ul>
    </div>
    
    <div class="banner-images">
      <%= link_to_add_association 'Agregar foto', f, :images, 'data-association-insertion-node'=>'.wrapper', 'data-association-insertion-traversal'=>'siblings', class: 'btn btn-default pull-right', 'data-association-insertion-method'=>'append', partial: "banners/image_fields" %>

      <h3>Fotos</h3> 
      <p class="text-info hint"><i class="fa fa-info-circle"></i> Puedes cambiar el orden de las fotos arrastrándolas con el icono de flechas. <strong>La primera imagen será la destacada</strong> y se mostrará en el listado de anuncios.</p>

      <div class="wrapper">
        <%= f.simple_fields_for :images do |i| %>
          <div class="nested-fields image">
            <%= f.input_field :position, as: :hidden %>
            <%= f.input_field :id, as: :hidden %>

            <div class="actions">
              <a href="#" class=" move-up"><i class="fa fa-arrow-up"></i></a>
              <a href="#" class=" move-down"><i class="fa fa-arrow-down"></i></a>
              <%= link_to_remove_association '<i class="fa fa-times"></i>'.html_safe, f, class: 'remove-item' %>
            </div>

            <%= f.input :file, label: "Imagen" %>
            <%= f.input_field :file_cache, as: :hidden %>
            
            <% if f.object.file? %>
              <%= link_to image_tag(f.object.file.url(:thumb)), f.object.file.url(:large), "data-fancybox" => "images", rel: 'gallery' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    
  </div>

  <div class="col-md-8 col-md-pull-4">

    <h2><%= title "Nuevo anuncio" %></h2>
    
      <%= f.error_notification %>
      <%#= @banner.errors.inspect %>

      <%= f.input :title, label: "Título" %>
      <div class="row">
        <div class="col-md-6">
          <%= f.association :category, label: "Categoría", include_blank: "- Selecciona" %>
        </div>
        <div class="col-md-6">
          <%= f.input :price, label: "Precio del servicio" %>
        </div>
      </div>
      
      <label class="control-label">Localización</label>
      <div class="row">
        <div class="col-md-6">
          <%= f.association :state, label: false, collection: State.all, include_blank: t('provincia'), input_html:{class: 'selectize-states'} %>
        </div>
        <div class="col-md-6">
          <% selected_city = @banner.state ? @banner.state.cities : [] %>
          <%= f.association :city, collection: selected_city, label: false, placeholder: 'Ciudad', input_html:{class: 'selectize-cities'} %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-12">
          <%= f.input :description, label: "Descripción", input_html: {class: 'summernote', data: {}} %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-6">
          <%= f.input :email, label: "Email", hint: 'Tu email NO será publicado' %>
        </div>
        <div class="col-md-6">
          <%= f.input :phone, label: "Teléfono", hint: "Sin espacios. #{Rails.application.secrets.phone_digits} caracteres exactos." %>
        </div>
      </div>

      <%= f.input :alerts, label: "Recibir alertas" %>
      <%= f.input :visible_from, label: 'Visible a partir de' %>

      <hr>

       <div class="row">
        <div class="col-md-12">
          <h3>Registrate o inicia sesión con tu Email y Contraseña</h3>
        </div>
      </div>

      <% if @user && @user.errors.present? %>
        <div class="hidden-print alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <div class="content">
            <%= @user.errors.full_messages.join(', ') %>
          </div>
        </div>
      <% end %>

      <!--
      <div class="row">
        <div class="col-md-6">
          <div class="form-group string required">
            <label class="control-label required" for="user_first_name"><abbr title="requerido">*</abbr> Nombre</label>
            <%#= text_field_tag :user_first_name, nil, required: 'required', class: "form-control string required" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group string required">
            <label class="control-label required" for="user_last_name"><abbr title="requerido">*</abbr> Apellidos</label>
            <%#= text_field_tag :user_last_name, nil, required: 'required', class: "form-control string required" %>
          </div>
        </div>
      </div>
      -->

      <div class="row">
        <div class="col-md-6">
          <div class="form-group string required">
            <label class="control-label required" for="user_email"><abbr title="requerido">*</abbr> Email</label>
            <%= email_field_tag :user_email, nil, required: 'required', class: "form-control string required" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group string required">
            <label class="control-label required" for="user_password"><abbr title="requerido">*</abbr> Contraseña</label>
            <%= password_field_tag :user_password, nil, required: 'required', class: "form-control string required" %>
          </div>
        </div>
      </div>

      <!--
      <div class="row">
        <div class="col-md-6">
          <div class="form-group string required">
            <label class="control-label required" for="user_password"><abbr title="requerido">*</abbr> Contraseña</label>
            <%#= password_field_tag :user_password, nil, required: 'required', class: "form-control string required" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group string required">
            <label class="control-label required" for="user_password_confirmation"><abbr title="requerido">*</abbr> Confirmar Contraseña</label>
            <%#= password_field_tag :user_password_confirmation, nil, required: 'required', class: "form-control string required" %>
          </div>
        </div>
      </div>
      -->

      <%= f.submit "Guardar anuncio", class: 'btn btn-lg btn-success' %>
      <%= link_to "Cancelar y volver", root_path, class: 'btn btn-lg btn-default' %>

  </div>

  <% end %>

</div>

app/views/banners/edit.html.erb
<%= render 'form' %>

app/views/banners/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to 'Nuevo anuncio', new_banner_path, class: 'btn btn-success' %>
    </div>
    
    <h1><%= title "Mis anuncios" %></h1>

    <% if @banners.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th class="hidden-xs">Categoría</th>
          <th class="hidden-xs">Ubicación</th>
          <th class="hidden-xs">Visualizaciones</th>
          <th class="" style="width:120px"></th>
        </tr>
      </thead>

      <tbody>
        <% @banners.each do |banner| %>
          <tr>
            <td>
              <%= link_to banner.title, post_permalink(banner) %>
              <% unless banner.validated %>
                <br />
                (Aún no has validado este anuncio)
                <%= link_to 'Reenviar email de validación', resend_email_validation_path(id: banner.slug) %>
              <% end %>
            </td>
            <td class="hidden-xs"><%= banner.category.title %></td>
            <td class="hidden-xs"><%= banner.location_name %></td>
            <td class="hidden-xs">
              Anuncio: <%= banner.impressions_count %><br>
              Telf: <%= banner.phone_views.size %>
            </td>
            <td class="">
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_banner_path(banner), class: 'btn btn-sm btn-default' %>
              <%= link_to '<i class="fa fa-star"></i>'.html_safe, "#{post_permalink(banner)}#post_payment_options", title: "Mejora tu plan", class: 'btn btn-sm btn-default' %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, banner, method: :delete, data: { confirm: '¿Estas seguro?' }, class: 'btn btn-sm btn-default' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @banners %>
    <% else %>
      <p>Aun no has creado ningún anuncio. <%= link_to "Crea uno aquí", new_banner_path %></p>
    <% end %>
    

  </div>
</div>

app/views/banners/new.html.erb
<% content_for :meta_robots do %>
  <meta name="robots" content="noindex,follow" />
<% end %>
<%= render 'form' %>