config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do

  # tanto WWW como SIN subdomain, hacen redirect
  constraints(subdomain: ['www','']) do
    scope as: 'www' do
      root to: 'country_selector#show'
      get '*path' => 'country_selector#show'
    end
  end

  draw :es_redirections
  draw :mx_redirections
  
  # el app solo acepta routes bajo el subdomain de su pais
  constraints(subdomain: Rails.configuration.x.app_country) do

    devise_for :super_users, controllers: {
      sessions: 'super/users/sessions',
      passwords: 'super/users/passwords',
    }

    ### SUPER
    namespace :super do
      resources :banners do
        get :toggle_recommended, on: :member
        post :delete_multiple_banners, on: :collection 
      end

      resources :payments
      resources :users
      resources :banner_categories
      resources :payment_types
      resources :pack_discounts
      resources :super_users
      resources :app_settings
      resources :html_texts
      resources :image_banners
      resources :external_banners

      get 'reportes'                       => 'reports#index',              as: 'reports'
      get 'reportes/titulos_duplicados'    => 'reports#duplicated_title',   as: 'duplicated_title_reports'
      get 'reportes/contenidos_duplicados' => 'reports#duplicated_content', as: 'duplicated_content_reports'
      get 'reportes/titulos_similares'     => 'reports#similar_title',      as: 'similar_title_reports'
      get 'reportes/contenidos_similares'  => 'reports#similar_content',    as: 'similar_content_reports'
      get 'reportes/usuarios'              => 'reports#users',              as: 'users_reports'
      get 'reportes/usuarios_semanal'      => 'reports#weekly_users',       as: 'weekly_users_reports'

      root to: 'users#index'

      match 'similar_text' => 'banners#similar_text', as: :similar_text, via: [:get, :post]
    end

    ### FRONTEND

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      # omniauth_callbacks: "users/omniauth_callbacks",
    }
    resources :users
    resources :banners

    get  'nuevo-anuncio-y-registro' => 'banners#anon_new_banner', as: 'anon_new_banner'
    post 'anon_create_banner' => 'banners#anon_create_banner', as: 'anon_create_banner'
    get '/users/sign_up', to: redirect('nuevo-anuncio-y-registro', status: 301)

    resources :cities do
      collection do
        get :search
      end
    end

    get '/anuncios-eroticos/escorts-y-putas/distrito-federal', to: redirect('/anuncios-eroticos/escorts-y-putas/distrito-federal-df', status: 301)

    # search url pretty para SEO
    # uso el keyword "putas" para crear variaciones de patrones segun los params pasados
    get '/nuevo-anuncio' => 'banners#new', as: "new_post"
    get '/anuncios-eroticos/:category/:state(/contactos/:term)' => "posts#index", as: "search_state_term"
    get '/anuncios-eroticos/:category(/contactos/:term)'        => "posts#index", as: "search_term"
    get '/anuncios-eroticos/:category(/:state)(/:city)(/:term)' => "posts#index", as: "friendly_search"
    get '/anuncios-eroticos/:category(/:state)(/:city)(/:term)' => "posts#index", as: "full_search"
    get '/anuncios-eroticos/:category' => "posts#index", as: "only_category"


    get '/anuncio-erotico/:id' => "posts#show", as: "post_with_category"
    get '/posts/:id/get_phone' => "posts#show_phone", as: 'post_phone'

    resources :posts, path: 'anuncios' do
      get :search, on: :collection
    end
    get '/anuncios-eroticos/:category_id/:state_id'          => 'posts#search_single_state', as: :search_single_state
    get '/anuncios-eroticos/:category_id/:state_id/:city_id' => 'posts#search_single_city',  as: :search_single_city

    resources :banner_contact_requests
    resources :user_favorites do
      post :toggle, on: :member
    end

    resources :sent_favorites
    resources :feedback_requests

    # pagos
    get '/historial-pagos' => 'payments#index', as: 'my_payments'
    get '/historial-pagos/:id' => 'payments#show', as: 'view_payment'
    get '/payments/est_price' => 'payments#get_price', as: 'est_price'
    resources :payments

    # paypal checkout
    get '/paypal/checkout' => 'paypal#checkout', as: 'paypal_checkout'
    get '/paypal/success' => 'paypal#success', as: 'paypal_success'
    get '/paypal/fail' => 'paypal#fail', as: 'paypal_fail'

    # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

    get '/mejora-adultguia' => 'feedback_requests#new', as: "feedback"
    get '/aviso-legal' => 'statics#aviso_legal', as: "aviso_legal"
    get '/politica-privacidad-cookies' => 'statics#politica_privacidad', as: "politica_privacidad"

    get 'feed' => 'posts#feed'

    root to: 'posts#index'

    get '/remote-cities' => 'cities#search', as: "remote_cities"

    post 'set_paid_location' => 'banners#set_paid_location', as: 'set_paid_location'

    get 'validar_anuncio' => 'banners#validate', as: 'validate_banner'
    get 'resend_email_validation' => 'banners#resend_email_validation', as: 'resend_email_validation'

  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  belongs_to :banner, -> { with_deleted }
  belongs_to :payment_type, -> { with_deleted }
  
  has_many :schedules, class_name: "PaymentSchedule", foreign_key: "payment_id"

  serialize :paypal_response
  serialize :aplicable_days_of_week

  DAYS_OF_WEEK = {
    'L'=>'1',
    'M'=>'2',
    'X'=>'3',
    'J'=>'4',
    'V'=>'5',
    'S'=>'6',
    'D'=>'0',
  }

  ### VALIDATION

  # base
  validates :banner, :payment_type, presence: true
  validates :price, presence: true, numericality: true
  validates :state, presence: true, inclusion: {in: ['cart','complete']}
  # optional
  validates :num_days, presence: true, numericality: {greater_than: 0}, if: " payment_type.uses_days? "
  validates :expire_at, presence: true, if: " state == 'complete' && payment_type.uses_days? "

  # pack custom
  validate :one_schedule_min

  # pack auto
  with_options if: " payment_type.code == 'subir_pack_auto' " do |a|
    a.validates :schedule_hour, presence: true, format: { with: PaymentSchedule::HOUR_REGEX }
    a.validates :schedule_min, presence: true, format: { with: PaymentSchedule::MIN_REGEX }
  end

  accepts_nested_attributes_for :schedules, allow_destroy: true

  ### SCOPES

  scope :complete, -> { where(state: 'complete') }
  # donde el servicio expire y aun no hayamos llegado a la expiración O
  # el payment sea one-time sin caducidad (como "destacar")
  scope :active, -> { complete.where(
    '(expire_at is not null and ? < expire_at) OR (payment_type_id = ?)',
    Time.now,
    PaymentType.find_by(code: 'destacar').id
    )
  }

  ### CALLBACKS

  before_validation do
    self.state = 'cart' if new_record?
  end
  before_create :set_expiration

  def set_expiration
    if payment_type.code == "subir_pack_custom" 
      last_date = schedules.map(&:run_at).sort().last
      self.expire_at = last_date
    end
  end

  def one_schedule_min
    if payment_type.code == "subir_pack_custom"
      errors.add :time_errors, "Selecciona al menos 1 hora" if schedules.empty?
      errors.add :time_errors, "Hay horas repetidas en tu selección" if schedules.map(&:min_hour).uniq!
      errors.add :schedule_errors, 'El numero de times != num_days' if parse_custom_times.size != num_days
      errors.add :start_date, 'El numero de times != num_days' if start_date <= Date.current
    end
  end

  ### OTHER

  def parse_custom_times
    jobs = []
    count = 0
    hours = schedules.map(&:min_hour).sort
    day = start_date
    num_days.times do |i|
      hours.each do |hh|
        if !day.wday.to_s.in?(aplicable_days_of_week)
          ap "skipping day #{day} / #{day.wday}"
          next
        end
        jobs << Time.parse("#{day.strftime('%Y-%m-%d')} #{hh}")
        count += 1
        break if count == num_days
      end
      break if count == num_days
      day = day + 1.day
    end
    jobs
  end

  def complete?
    state == 'complete'
  end

  def process(data)
    self.paypal_response = data
    if data.ack == "Success"
      self.state = 'complete'
      # seteamos fecha de expiración si este tipo de pago usa dias
      if payment_type.uses_days?
        self.expire_at = num_days.days.from_now
      end
      if payment_type.code == 'subir_pack_custom'
        self.expire_at = parse_custom_times.last
      end
    end
    save!

    # apply promo action
    if complete?
      PaymentType.apply(payment_type.id, banner_id, self)
    end
  end

end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  acts_as_paranoid

  TYPES = ['subir', 'subir_pack_auto', 'subir_pack_custom', 'destacar', 'top', 'publish']

  has_many :discounts, class_name: "PackDiscount", foreign_key: "payment_type_id"

  validates :code, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :description, allow_blank: true, length: {maximum: 200}

  accepts_nested_attributes_for :discounts, allow_destroy: true

  scope :non_publish, -> { where.not(code: 'publish') }

  # tipos de pago que aplican para descuento (segun rangos de dias)
  def discount_elegible?
    ['destacar', 'top', 'subir_pack_custom', 'subir_pack_auto'].include?(code)
  end

  # para saber si validar el campo :num_days del payment
  def uses_days?
    ['destacar', 'top', 'subir_pack_auto'].include?(code)
  end

  def get_price(opts={})
    opts.reverse_merge!({
      days: 1
    })

    disc_total = 0
    if discount_elegible?
      disc_total = price * get_discount_percent(opts[:days])
      aplicable_price = (price - disc_total).round(2)
    else
      aplicable_price = price # default base
    end

    (aplicable_price * opts[:days]).round(2)
  end

  def get_discount_percent(days)
    rec = discounts.where(':num_days BETWEEN days_from and days_to OR :num_days > days_to', num_days: days).order('discount desc').first
    rec ? (rec.discount / 100) : 0
  end

  ### CLASS

  # Callback tras hacer el pago successfully, ejecuta la acción de promoción
  # correspondiente
  def self.apply(type_id, banner_id, payment)
    type = PaymentType.find(type_id)
    banner = Banner.find(banner_id)
    case type.code
    # instantaneo
    when "subir"
      # update del campo "sort_date" en banners
      banner.update_column :sort_date, Time.now
    when 'destacar'
      banner.update_column :is_featured, true
      Banner.delay(run_at: payment.expire_at).expire_featured(banner.id)
    # instantaneo, solo programo la expiración en DJ
    when 'top'
      banner.update_column :is_top, true
      Banner.delay(run_at: payment.expire_at).expire_top(banner.id)
    when 'subir_pack_custom'
      # segun las fechas indicadas por el user, las meto tal cual en DJ
      payment.parse_custom_times.each do |date|
        Banner.delay(run_at: date).move_top(banner.id)
      end
    when 'subir_pack_auto'
      # le resto un dia, ya que si lo contrato el 28 de nov, empieza a contabilizar
      # al dia siguiente 29 nov. El ultimo dia es "inclusive" tambien
      start_at = (payment.expire_at - (payment.num_days-1).days).to_date
      end_at = payment.expire_at.to_date
      # creo los jobs en DJ
      (start_at..end_at).to_a.each do |date|
        run_at = Time.parse("#{date.strftime('%Y-%m-%d')} #{payment.schedule_hour}:#{payment.schedule_min}")
        Banner.delay(run_at: run_at).move_top(banner.id)
      end
    end
  end

  def publish_banner?
    code == 'publish'
  end

end

app/controllers/payments_controller.rb
class PaymentsController < BaseController

  before_action :authenticate_user!

  def index
    @payments = with_deleted_scope
                .order('id desc')
                .page(params[:page]).per(20)
  end

  def show
    @payment = with_deleted_scope.find(params[:id])
    @existing_schedules = @payment.parse_custom_times if @payment.payment_type.code == "subir_pack_custom"
  end
  
  def new
    # si hay que personalizar alguna opción, se hace aquí (render view)
    @type = PaymentType.find(params[:type])
    @banner = current_user.banners.find(params[:banner])

    days = params[:days] ? params[:days].to_i : 1
    @payment = @banner.payments.new(
      payment_type: @type,
      price: @type.price,
      total: @type.get_price(days: days),
      discount_percent: @type.get_discount_percent(days),
      num_days: days,
      aplicable_days_of_week: Payment::DAYS_OF_WEEK.values,
      start_date: I18n.l(1.day.from_now, format: '%d/%m/%Y')
    )

    # sino, hacemos redirect a checkout de paypal
    if ['subir', 'destacar', 'top'].include?(@type.code)
      @payment.save!
      session[:payment_id] = @payment.id

      redirect_to paypal_checkout_path
      return
    end

    # se necesita un form para personalizar mas las opciones?
    case @type.code
    when "subir_pack_custom"
      date = 1.day.from_now
      @payment.schedules.build(
        time_hour: date.strftime("%H"),
        time_min: date.strftime("%M"),
      )
      # dias programados existentes para este banner
      @existing_schedules = @banner.payments.active.where(payment_type_id: @type.id).map(&:parse_custom_times).flatten
    when "subir_pack_auto"

    end

  end

  def create
    @payment = current_user.payments.new(s_params)
    @type = @payment.payment_type
    @banner = @payment.banner

    @payment.price = @type.price
    @payment.total = @type.get_price(days: @payment.num_days)
    @payment.discount_percent = @type.get_discount_percent(@payment.num_days)

    if @payment.save
      # go to payment...
      session[:payment_id] = @payment.id
      redirect_to paypal_checkout_path
    else
      render :new
    end
  end

  def get_price
    type = PaymentType.find(params[:type])
    render json: {price: type.get_price(days: params[:days].to_i) }.to_json
  end

  private

  # unscope banners para acceder tambien a los soft-deleted
  def with_deleted_scope
    banners_ids = current_user.banners.with_deleted.pluck(:id)
    Payment
          .includes(:banner, :payment_type)
          .where(banner: banners_ids )
          .complete
  end

  def s_params
    params.require(:payment).permit(:banner_id, :payment_type_id, :num_days, :schedule_hour, :schedule_min, :start_date, :aplicable_days_of_week => [], :schedules_attributes => [:id, :time_hour, :time_min, :_destroy])
  end

end

app/controllers/super/payments_controller.rb
module Super

class PaymentsController < Super::BaseController
  
  def index
    @q = Payment.complete.includes(:banner, :payment_type).ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @payments = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def show
    @payment = Payment.includes(:banner, :payment_type).find(params[:id])
    @existing_schedules = @payment.parse_custom_times if @payment.payment_type.code == "subir_pack_custom"
  end

end

end

app/views/payments/_schedule_fields.html.erb
<div class="nested-fields">
  <%= link_to_remove_association '<i class="fa fa-times"></i>'.html_safe, f, class: 'remove' %>
  
  <%= f.input_field :id, as: :hidden %>
  
  <%#= f.input :date, label: false, as: :string, input_html:{ class: 'datepicker' } %>
  <label>A las:</label>
  <%= f.input :time_hour, label: false, pattern: "^([0-9]|0[0-9]|1[0-9]|2[0-3])$", placeholder: '00', input_html:{ class: 'sm' } %>
  <%= f.input :time_min, label: false, pattern: "^[0-5][0-9]$", placeholder: '00', input_html:{ class: 'sm' } %>

  <%= f.error :date %>
  <%= f.error :invalid_date %>

</div>

app/views/payments/_subir_pack_auto_form.html.erb
<%= simple_form_for @payment, html: {class: 'payment-form auto'} do |f| %>

  <div class="row">
    <div class="col-md-8">
      <%= f.error :schedule_errors %>

      <%#= @payment.errors.inspect %>
      <%#= @payment.total %>

      <%= f.input_field :banner_id, as: :hidden %>
      <%= f.input_field :payment_type_id, as: :hidden %>

      <p>El formato de hora es de 0:00 a 24:00, así las 7:15 son de la mañana y las 19:15 de la tarde.</p>

      <div class="row">
        <div class="col-md-4">
          <label for="">Número de dias</label>
          <%= f.input :num_days, label: false, required: true, input_html: { min: 1, max: 999 } %>
        </div>
        <div class="col-md-6">
          <label for="">A las</label>
          <%= f.input :schedule_hour, required: true, label: false, placeholder: "00", input_html:{class: 'sm'}, pattern: "^([0-9]|0[0-9]|1[0-9]|2[0-3])$" %>
          <%= f.input :schedule_min, required: true, label: false, placeholder: "00", input_html:{class: 'sm'}, pattern: "^[0-5][0-9]$" %>
        </div>
      </div>
      
    </div>
    
    <div class="col-md-4">
      <% if @type.discounts.any? %>
        <h5>Precios según volumen</h5>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Rango</th>
              <th>Descuento</th>
              <th>Precio / día</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1 dia</td>
              <td></td>
              <td>
                <%= number_with_precision @payment.price, precision: 2 %>
                <%= money_symbol %>
              </td>
            </tr>
            <% @type.discounts.each do |d| %>
            <tr>
              <td><%= "#{d.days_from}-#{d.days_to} días" %></td>
              <td><%= d.discount.to_i %>%</td>
              <td>
                <%= @type.price - (@type.price * (d.discount/100) ) %>
                <%= money_symbol %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>

  </div>

  <div class="payment-total">
    <strong>Coste del servicio</strong> (IVA inc): <span></span>
  </div>

  <%= f.submit "Confirmar pedido", class: 'btn btn-primary btn-lg' %>

<% end %>

app/views/payments/_subir_pack_custom_form.html.erb
<% if @existing_schedules.present? %>
  <div class="alert alert-info existing-schedules">
    <h4><i class="fa fa-exclamation-triangle"></i> Actualmente tienes <%= @existing_schedules.size %> subidas programadas para este anuncio:</h4>
    <ul>
      <% @existing_schedules.each do |dd| %>
        <li><%= l dd, format: :short %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @payment, html: {class: 'payment-form custom'} do |f| %>

  <div class="row">
    <div class="col-md-8">
      <%= f.error :schedule_errors %>
      
      <div class="row">
        <div class="col-md-6">
          <h4>Número de veces</h4>
          <%= f.input :num_days, label: 'Indica el número de veces que deseas subir tu anuncio', input_html: {min: 1} %>

          <%= f.input :aplicable_days_of_week, label: 'Dias que quieres que salga', collection: Payment::DAYS_OF_WEEK, as: :check_boxes, input_html: {multiple: true} %>

          <%= f.input :start_date, as: :string, label: '¿Cuando quieres empezar a aparecer?', input_html: {class: 'start-date-picker'} %>
        </div>
        <div class="col-md-6">
          <h4>Horas</h4>
          <p>Selecciona la(s) hora(s) a las que deseas subir tu anuncio. Para agregar otra hora haz click en "Agregar otra hora".</p>
          <p>El formato de hora es de 0:00 a 24:00, así las 7:15 son de la mañana y las 19:15 de la tarde.</p>

          <div class="payment-schedules">
            <div class="wrapper">
              <%= f.simple_fields_for :schedules do |s| %>
                <%= render 'schedule_fields', f: s %>
              <% end %>
            </div>
            <%= f.error :time_errors %>
            <div class="clearfix"></div>
            <%= link_to_add_association 'Agregar otra hora', f, :schedules, 'data-association-insertion-node'=>'.wrapper', 'data-association-insertion-traversal'=>'siblings', 'data-association-insertion-method'=>'append', class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      </div>

      <%= f.input_field :banner_id, as: :hidden %>
      <%= f.input_field :payment_type_id, as: :hidden %>
      
    </div>
    
    <div class="col-md-4">
      <% if @type.discounts.any? %>
        <h5>Precios según volumen</h5>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Rango</th>
              <th>Descuento</th>
              <th>Precio / día</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1 dia</td>
              <td></td>
              <td>
                <%= number_with_precision @payment.price, precision: 2 %>
                <%= money_symbol %>
              </td>
            </tr>
            <% @type.discounts.each do |d| %>
            <tr>
              <td><%= "#{d.days_from}-#{d.days_to} días" %></td>
              <td><%= d.discount.to_i %>%</td>
              <td>
                <%= @type.price - (@type.price * (d.discount/100)).round(2) %>
                <%= money_symbol %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>

  </div>

  <div class="payment-total">
    <strong>Coste del servicio</strong> (IVA inc): <span></span>
  </div>

  <%= f.submit "Confirmar pedido", class: 'btn btn-primary btn-lg submit-form' %>

<% end %>

app/views/payments/index.html.erb
<h2>Historial de pagos</h2>

<% if @payments.any? %>

  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Anuncio</th>
        <th class="hidden-xs">Tipo</th>
        <th class="hidden-xs">Fecha</th>
        <th class="hidden-xs">Referencia</th>
        <th class="text-right hidden-xs">Importe</th>
        <th style="width:100px"></th>
      </tr>
    </thead>
    <tbody>
      <% @payments.each do |p| %>
        <tr>
          <% pp = p.paypal_response %>
          <td >
            <span class="text-primary"><%= p.banner.title %></span>
            <div class="visible-xs">
              Tipo: <%= p.payment_type.title %><br>
              <strong>Importe:</strong> <%= show_money pp.amount.total %>
            </div>
          </td>
          <td class="hidden-xs"><%= p.payment_type.title %></td>
          <td class="hidden-xs"><%= l pp.order_time.to_datetime, format: :short %></td>
          <td class="hidden-xs"><%= pp.transaction_id %></td>
          <td class="text-right hidden-xs"><%= show_money pp.amount.total %></td>
          <td>
            <%= link_to 'ver detalles', view_payment_path(p), class: '' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @payments %>

<% else %>

  <p class="text-warning">No hay transacciones que mostrar.</p>

<% end %>

app/views/payments/new.html.erb
<% content_for :js_init do %>
  <script>
    (function(){
      var form = new PaymentForm(<%= raw @type.to_json %>);
    })();
  </script>
<% end %>

<h2><%= @type.title %></h2>
<h4><%= link_to @banner.title, post_path(@banner) %></h4>
<hr>

<%= render "#{@type.code}_form" %>

app/views/payments/show.html.erb
<div class="pull-right">
  <%= link_to "Volver al listado", my_payments_path, class: 'btn btn-default' %>
</div>

<h1>Detalles de la transacción</h1>

<% pp = @payment.paypal_response %>

<div class="row">
  <div class="col-md-8">
    
    <table class="table">
      <tbody>
        <tr>
          <td>Anuncio</td>
          <td><%= @payment.banner.title %></td>
        </tr>
        <tr>
          <td>Tipo de pago</td>
          <td><%= @payment.payment_type.title %></td>
        </tr>
        <tr>
          <td>Referencia</td>
          <td><%= pp.transaction_id %></td>
        </tr>
        <tr>
          <td>Fecha</td>
          <td><%= l pp.order_time.to_datetime, format: :short %></td>
        </tr>
        <tr>
          <td>Importe</td>
          <td><%= show_money pp.amount.total %></td>
        </tr>
        <% if @payment.expire_at %>
          <tr>
            <td>Fecha expiración</td>
            <td><%= l @payment.expire_at, format: :short %></td>
          </tr>
        <% end %>
        <% if @payment.payment_type.uses_days? %>
          <tr>
            <td>Número de días contratados</td>
            <td><%= @payment.num_days %></td>
          </tr>
          <tr>
            <td>Descuento aplicado</td>
            <td><%= number_with_precision @payment.discount_percent * 100, precision: 2 %>%</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <!-- pack custom -->
    <% if @existing_schedules.present? %>
      <div class="alert alert-warning">
        <h4><i class="fa fa-calendar"></i> Subidas programadas de este pago:</h4>
        <ul>
          <% @existing_schedules.each do |dd| %>
            <li><%= l dd, format: :short %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- pack auto -->
    <% if @payment.payment_type.code == "subir_pack_auto" %>
      <div class="alert alert-warning">
        <h4><i class="fa fa-calendar"></i> Subidas programadas de este pago:</h4>
        <%
          start_at = (@payment.expire_at - (@payment.num_days-1).days).to_date
          end_at = @payment.expire_at.to_date
        %>
        <ul>
        <% (start_at..end_at).to_a.each do |date| %>
          <% run_at = Time.parse("#{date.strftime('%Y-%m-%d')} #{@payment.schedule_hour}:#{@payment.schedule_min}") %>
          <li><%= l run_at, format: :short %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  </div>
</div>