config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do

  # tanto WWW como SIN subdomain, hacen redirect
  constraints(subdomain: ['www','']) do
    scope as: 'www' do
      root to: 'country_selector#show'
      get '*path' => 'country_selector#show'
    end
  end

  draw :es_redirections
  draw :mx_redirections
  
  # el app solo acepta routes bajo el subdomain de su pais
  constraints(subdomain: Rails.configuration.x.app_country) do

    devise_for :super_users, controllers: {
      sessions: 'super/users/sessions',
      passwords: 'super/users/passwords',
    }

    ### SUPER
    namespace :super do
      resources :banners do
        get :toggle_recommended, on: :member
        post :delete_multiple_banners, on: :collection 
      end

      resources :payments
      resources :users
      resources :banner_categories
      resources :payment_types
      resources :pack_discounts
      resources :super_users
      resources :app_settings
      resources :html_texts
      resources :image_banners
      resources :external_banners

      get 'reportes'                       => 'reports#index',              as: 'reports'
      get 'reportes/titulos_duplicados'    => 'reports#duplicated_title',   as: 'duplicated_title_reports'
      get 'reportes/contenidos_duplicados' => 'reports#duplicated_content', as: 'duplicated_content_reports'
      get 'reportes/titulos_similares'     => 'reports#similar_title',      as: 'similar_title_reports'
      get 'reportes/contenidos_similares'  => 'reports#similar_content',    as: 'similar_content_reports'
      get 'reportes/usuarios'              => 'reports#users',              as: 'users_reports'
      get 'reportes/usuarios_semanal'      => 'reports#weekly_users',       as: 'weekly_users_reports'

      root to: 'users#index'

      match 'similar_text' => 'banners#similar_text', as: :similar_text, via: [:get, :post]
    end

    ### FRONTEND

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      # omniauth_callbacks: "users/omniauth_callbacks",
    }
    resources :users
    resources :banners

    get  'nuevo-anuncio-y-registro' => 'banners#anon_new_banner', as: 'anon_new_banner'
    post 'anon_create_banner' => 'banners#anon_create_banner', as: 'anon_create_banner'
    get '/users/sign_up', to: redirect('nuevo-anuncio-y-registro', status: 301)

    resources :cities do
      collection do
        get :search
      end
    end

    get '/anuncios-eroticos/escorts-y-putas/distrito-federal', to: redirect('/anuncios-eroticos/escorts-y-putas/distrito-federal-df', status: 301)

    # search url pretty para SEO
    # uso el keyword "putas" para crear variaciones de patrones segun los params pasados
    get '/nuevo-anuncio' => 'banners#new', as: "new_post"
    get '/anuncios-eroticos/:category/:state(/contactos/:term)' => "posts#index", as: "search_state_term"
    get '/anuncios-eroticos/:category(/contactos/:term)'        => "posts#index", as: "search_term"
    get '/anuncios-eroticos/:category(/:state)(/:city)(/:term)' => "posts#index", as: "friendly_search"
    get '/anuncios-eroticos/:category(/:state)(/:city)(/:term)' => "posts#index", as: "full_search"
    get '/anuncios-eroticos/:category' => "posts#index", as: "only_category"


    get '/anuncio-erotico/:id' => "posts#show", as: "post_with_category"
    get '/posts/:id/get_phone' => "posts#show_phone", as: 'post_phone'

    resources :posts, path: 'anuncios' do
      get :search, on: :collection
    end
    get '/anuncios-eroticos/:category_id/:state_id'          => 'posts#search_single_state', as: :search_single_state
    get '/anuncios-eroticos/:category_id/:state_id/:city_id' => 'posts#search_single_city',  as: :search_single_city

    resources :banner_contact_requests
    resources :user_favorites do
      post :toggle, on: :member
    end

    resources :sent_favorites
    resources :feedback_requests

    # pagos
    get '/historial-pagos' => 'payments#index', as: 'my_payments'
    get '/historial-pagos/:id' => 'payments#show', as: 'view_payment'
    get '/payments/est_price' => 'payments#get_price', as: 'est_price'
    resources :payments

    # paypal checkout
    get '/paypal/checkout' => 'paypal#checkout', as: 'paypal_checkout'
    get '/paypal/success' => 'paypal#success', as: 'paypal_success'
    get '/paypal/fail' => 'paypal#fail', as: 'paypal_fail'

    # match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

    get '/mejora-adultguia' => 'feedback_requests#new', as: "feedback"
    get '/aviso-legal' => 'statics#aviso_legal', as: "aviso_legal"
    get '/politica-privacidad-cookies' => 'statics#politica_privacidad', as: "politica_privacidad"

    get 'feed' => 'posts#feed'

    root to: 'posts#index'

    get '/remote-cities' => 'cities#search', as: "remote_cities"

    post 'set_paid_location' => 'banners#set_paid_location', as: 'set_paid_location'

    get 'validar_anuncio' => 'banners#validate', as: 'validate_banner'
    get 'resend_email_validation' => 'banners#resend_email_validation', as: 'resend_email_validation'

  end

end

app/controllers/super/app_settings_controller.rb
module Super

  class AppSettingsController < Super::BaseController

    def index
      @settings = AppSetting.where(key: 'auto_subir_old_posts')
    end

    def update
      setting = AppSetting.find(params[:id])
      if setting.update(s_params)
        render json: setting.to_json
      else
      end
    end

    private

    def s_params
      params.require(:app_setting).permit!
    end

  end

end

app/controllers/super/banner_categories_controller.rb
module Super

class BannerCategoriesController < Super::BaseController
  
  def index
    @categories = BannerCategory.page(params[:page]).per(20)
  end

  def new
    @category = BannerCategory.new
  end

  def create
    @category = BannerCategory.new(s_params)
    if @category.save
      redirect_to super_banner_categories_url, notice: "Categoría creada"
    else
      render :new
    end
  end

  def edit
    @category = BannerCategory.friendly.find(params[:id])
  end

  def update
    @category = BannerCategory.friendly.find(params[:id])
    if @category.update(s_params)
      redirect_to edit_super_banner_category_path(@category), notice: "Cambios guardados"
    else
      render :edit
    end
  end

  def destroy
    categ = BannerCategory.friendly.find(params[:id])
    categ.destroy
    redirect_to super_banner_categories_url, notice: 'Categoría eliminada'
  end

  private

  def s_params
    params.require(:banner_category).permit!
  end

end

end

app/controllers/super/banners_controller.rb
module Super

  class BannersController < Super::BaseController
    
    def index
      @q = Banner.ransack(params[:q])
      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @banners = @q.result(distinct: true).page(params[:page]).per(20)
    end

    def edit
      @banner = Banner.friendly.find(params[:id])
    end

    def update
      @banner = Banner.friendly.find(params[:id])
      if @banner.update(s_params)
        redirect_to edit_super_banner_url(@banner), notice: "Cambios guardados"
      else
        render :edit
      end
    end

    def destroy
      banner = Banner.friendly.find(params[:id])
      banner.destroy
      redirect_to super_banners_url, notice: 'Anuncio eliminado'
    end

    def toggle_recommended
      banner = Banner.friendly.find(params[:id])
      banner.toggle :recommended
      banner.save
      
      notice_text = (banner.recommended == true) ? 'Anuncio marcado como recomendado' : 'Anuncio desmarcado como recomendado'
      redirect_to super_banners_url, notice: notice_text
    end

    def delete_multiple_banners
      params["delete_banner_id"].each do |banner_id|
        banner = Banner.find(banner_id)
        banner.destroy
      end

      redirect_to super_banners_url, notice: 'Anuncios eliminados'
    end

    def similar_text
      if request.post?
        #@similar_text = params[:text1].similar(params[:text2])
        @similar_text = Banner.compare_texts(params[:text1], params[:text2])
      end
    end

    private

    def s_params
      params.require(:banner).permit!
    end
    
  end

end

app/controllers/super/base_controller.rb
class Super::BaseController < ApplicationController

  before_action :authenticate_super_user!

  layout 'super'

end

app/controllers/super/external_banners_controller.rb
module Super

  class ExternalBannersController < Super::BaseController
    before_action :set_banner, only: [:index, :edit, :update]

    def index
    end

    def edit
    end

    def update
      @banner.update(banner_params)
      redirect_to super_external_banners_path, notice: 'Banners Actualizados'
    end

    private
      def set_banner
        @banner = ExternalBanner.first
      end

      def banner_params
        params.require(:external_banner).permit(:es_mobile, :mx_mobile, :es_desktop, :mx_desktop)
      end
  end
end

app/controllers/super/html_texts_controller.rb
module Super

  class HtmlTextsController < Super::BaseController
    before_action :set_html_text, only: [:show, :edit, :update, :destroy]

    def index
      @html_texts = HtmlText.all
    end

    def new
      @html_text = HtmlText.new
    end

    def edit
    end

    def create
      @html_text = HtmlText.new(html_text_params)
      if @html_text.save
        msg = 'Texto HTML Creado'
      else
        msg = @html_text.errors.full_messages.join(', ')
      end

      redirect_to super_html_texts_url, notice: msg
    end

    def update
      @html_text.update(html_text_params)
      redirect_to super_html_texts_url, notice: 'Texto HTML Actualizado'
    end

    def destroy
      @html_text.destroy
      redirect_to super_html_texts_url, notice: 'Texto HTML Eliminado'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_html_text
        @html_text = HtmlText.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def html_text_params
        params.require(:html_text).permit(:banner_category_id, :city_id, :state_id, :html_block, :active)
      end
  end
end

app/controllers/super/image_banners_controller.rb
module Super

  class ImageBannersController < Super::BaseController
    before_action :set_image_banner, only: [:show, :edit, :update, :destroy]

    def index
      @image_banners = ImageBanner.all
    end

    def new
      @image_banner = ImageBanner.new
    end

    def edit
    end

    def create
      @image_banner = ImageBanner.new(image_banner_params)
      if @image_banner.save
        msg = 'Banner Creado'
      else
        msg = @image_banner.errors.full_messages.join(', ')
      end

      redirect_to super_image_banners_url, notice: msg
    end

    def update
      @image_banner.update(image_banner_params)
      redirect_to super_image_banners_url, notice: 'Banner Actualizado'
    end

    def destroy
      @image_banner.destroy
      redirect_to super_image_banners_url, notice: 'Banner Eliminado'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image_banner
        @image_banner = ImageBanner.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def image_banner_params
        params.require(:image_banner).permit(:banner_category_id, :city_id, :state_id, :desktop_image, :mobile_image,
          :desktop_link, :mobile_link, :all_locations, :start_date, :end_date, :active)
      end
  end
end

app/controllers/super/payment_types_controller.rb
module Super

class PaymentTypesController < Super::BaseController
  
  def index
    @types = PaymentType.page(params[:page]).per(20)
  end

  def edit
    @type = PaymentType.find(params[:id])
  end

  def update
    @type = PaymentType.find(params[:id])
    if @type.update(s_params)
      redirect_to edit_super_payment_type_path(@type), notice: "Cambios guardados"
    else
      render :edit
    end
  end

  private

  def s_params
    params.require(:payment_type).permit(:title, :description, :price, :active, discounts_attributes: [:id, :_destroy, :days_from, :days_to, :discount])
  end

end

end

app/controllers/super/payments_controller.rb
module Super

class PaymentsController < Super::BaseController
  
  def index
    @q = Payment.complete.includes(:banner, :payment_type).ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @payments = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def show
    @payment = Payment.includes(:banner, :payment_type).find(params[:id])
    @existing_schedules = @payment.parse_custom_times if @payment.payment_type.code == "subir_pack_custom"
  end

end

end

app/controllers/super/reports_controller.rb
module Super

  class ReportsController < Super::BaseController
    
    def index
    end

    def duplicated_title
      banners = Banner.select(:title).group(:title).having("count(*) > 1")
      @banners = Banner.where(title: banners.collect(&:title))
    end

    def similar_title
      banners = Banner.last(300)
      repeated = []

      banners.each do |main_banner|
        banners.each do |banner|
          if is_similar?(main_banner.title, banner.title) && main_banner != banner
            repeated << main_banner if !repeated.include?(main_banner)
            repeated << banner if !repeated.include?(banner)
            repeated << "-"
          end
        end
      end
      
      @banners = repeated
    end

    def duplicated_content
      banners = Banner.select(:description).group(:description).having("count(*) > 1")
      @banners = Banner.where(description: banners.collect(&:description))
    end

    def similar_content
      banners = Banner.last(100)
      repeated = []

      banners.each do |main_banner|
        banners.each do |banner|
          if is_similar?(main_banner.description, banner.description) && main_banner != banner
            repeated << main_banner if !repeated.include?(main_banner)
            repeated << banner if !repeated.include?(banner)
            repeated << "-"
          end
        end
      end
      
      @banners = repeated
    end

    def users
      date  = Date.parse("sunday")
      delta = date < Date.today ? 0 : 7
      @week = date + delta
      
      weeks = []
      (1..30).each_with_index{ |w,i| weeks << [(@week.to_date - i.week).to_formatted_s(:long), i] }
      @weeks = weeks

      if params[:week].present?
        @filter = true
        @week = @week - params[:week].to_i.week
        @users = User.all.joins(:banners).where('banners.created_at between ? and ?', @week, @week + 1.week).uniq.page(params[:page]).per(200)
        @filter_msg = "de la semana: #{@week}"
      else
        @users = User.all.page(params[:page]).per(200)
        @filter_msg = 'de todos los tiempos'
      end
    end

    def weekly_users
      @users = []
    end

    def is_similar?(string_1, string_2, percent = 70)
      similar_percent = string_1.similar(string_2).to_i
      return (similar_percent >= percent) ? true : false
    end
  
  end

end

app/controllers/super/super_users_controller.rb
module Super

class SuperUsersController < Super::BaseController
  
  def index
    @users = SuperUser.page(params[:page]).per(20)
  end

  def new
    @user = SuperUser.new
  end

  def create
    @user = SuperUser.new(s_params)
    if @user.save
      redirect_to super_super_users_url, notice: "Usuario creado"
    else
      render :new
    end
  end

  def edit
    @user = SuperUser.find(params[:id])
  end

  def update
    @user = SuperUser.find(params[:id])
    if @user.update(s_params)
      redirect_to edit_super_super_user_path(@user), notice: "Cambios guardados"
    else
      render :edit
    end
  end

  def destroy
    user = SuperUser.find(params[:id])
    user.destroy
    redirect_to super_super_users_url, notice: 'Usuario eliminado'
  end

  private

  def s_params
    params.require(:super_user).permit!
  end

end

end

app/controllers/super/users/passwords_controller.rb
class Super::Users::PasswordsController < Devise::PasswordsController

  layout 'super'
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/super/users/sessions_controller.rb
class Super::Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  
  layout 'super'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/views/super/image_banners/_form.html.erb
<h2><%= @image_banner.new_record? ? "Nuevo" : "Editar" %> Banner</h2>

<%= simple_form_for [:super, @image_banner] do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-md-6">
      <%= f.association :banner_category, label: 'Categoría', include_blank: false, input_html: {required: true} %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.association :state, label: 'Estado', input_html: {required: true} %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.association :city, label: 'Ciudad' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <label>Imágen Desktop</label>
      <br/>
      <%= image_tag @image_banner.desktop_image.url(:thumb)  %>
      <%= f.file_field :desktop_image, input_html: {required: true} %>
    </div>
  </div>

  <br />

  <div class="row">
    <div class="col-md-6">
      <%= f.input :desktop_link, label: 'Link Desktop', input_html: {required: true} %>
    </div>
  </div>

  <br />

  <div class="row">
    <div class="col-md-6">
      <label>Imágen Móvil</label>
      <br/>
      <%= image_tag @image_banner.mobile_image.url(:thumb) %>
      <%= f.file_field :mobile_image, input_html: {required: true} %>
    </div>
  </div>

  <br />

  <div class="row">
    <div class="col-md-6">
      <%= f.input :mobile_link, label: 'Link Móvil', input_html: {required: true} %>
    </div>
  </div>

  <br />

  <div class="row">
    <div class="col-md-6">
      <label>Fecha Inicio</label>
      <br/>
      <%= f.date_select :start_date %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <label>Fecha Fin</label>
      <br/>
      <%= f.date_select :end_date %>
    </div>
  </div>

  <br />

  <div class="row">
    <div class="col-md-6">
      <%= f.check_box :active %>
      &nbsp;
      <label for='image_banner_active'>Activo ?</label>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.check_box :all_locations %>
      &nbsp;
      <label for='image_banner_all_locations'>Mostrar en todas las ubicaciones</label>
      <br >
      <small>
        Al seleccionar esta casilla, no se tendrán en cuenta los filtros catgoría y ubicación
      </small>
    </div>
  </div>

  <br />

  <%= f.submit "Guardar", class: 'btn btn-success btn-lg' %>
  <%= link_to "Volver", super_image_banners_path, class: 'btn btn-lg btn-default' %>

<% end %>

<script type="text/javascript">
  $("#image_banner_all_locations").click(function() {
    if($("#image_banner_all_locations").is(':checked')) {
      $("#image_banner_state_id").attr("disabled", true);
      $("#image_banner_city_id").attr("disabled", true);
    } else {
      $("#image_banner_state_id").attr("disabled", false);
      $("#image_banner_city_id").attr("disabled", false);
    }
  });
</script>

app/views/super/image_banners/edit.html.erb
<%= render 'form' %>

app/views/super/image_banners/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to "Nuevo Banner", new_super_image_banner_path, class: 'btn btn-success' %>
    </div>
    <h1>BANNERS</h1>

    <% if @image_banners.any? %>
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Categoría</th>
            <th>Estado</th>
            <th>Ciudad</th>
            <th>Imágen Desktop</th>
            <th>Imágen Móvil</th>
            <th>Fechas</th>
            <th>Activo?</th>
            <th>En todas las ubicaciones?</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @image_banners.each do |image_banner| %>
          <tr>
            <td><%= image_banner.banner_category.title %></td>
            <td><%= image_banner.state.name if image_banner.state %></td>
            <td><%= image_banner.city.name if image_banner.city %></td>
            <td>
              <%= image_tag image_banner.desktop_image.url(:thumb)  %>
              <br/>
              <%= link_to truncate(image_banner.desktop_link), image_banner.desktop_link, target: '_blank' %>
            </td>
            <td>
              <%= image_tag image_banner.mobile_image.url(:thumb) %>
              <br/>
              <%= link_to truncate(image_banner.mobile_link), image_banner.mobile_link, target: '_blank' %>
            </td>
            <td><%= image_banner.date_range %></td>
            <td><%= image_banner.active? ? 'SI' : 'NO' %></td>
            <td><%= image_banner.all_locations? ? 'SI' : '' %></td>
            <td class='text-right'>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_super_image_banner_path(image_banner), class: 'btn btn-default btn-sm' %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, [:super, image_banner], method: :delete, data: {confirm: "¿Seguro?"}, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

  </div>
</div>

app/views/super/image_banners/new.html.erb
<%= render 'form' %>